version: 2

models:
  - name: dim_products
    description: Information about each product
    columns:
      - name: name
        tests:
          - not_null
      - name: price
        tests:
          - positive_values
      - name: total_orders
        tests:
          - positive_values
      - name: inventory
        tests:
          - positive_values
  - name: dim_users
    description: Contains information about each user
    columns:
      - name: user_guid
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: total_orders_count
        tests:
          - not_null
      - name: first_order_at
        tests:
          - not_null
      - name: latest_order_at
        tests:
          - not_null
  - name: fct_orders
    description: Contains information about each order 
    columns:
      - name: order_guid
        tests:
          - not_null
      - name: user_guid
        tests:
          - not_null
      - name: order_cost
        tests:
          - not_null
      - name: order_total
        tests:
          - not_null